### ISSUE TITLE
请问我访问出现问题，帮忙解答一下，python不是很熟悉

### ISSUE THREAD

**Issue by skkep** [yanwii/msxiaoiceapi#3]
```
(env) aaaaa@ubuntu:/data/xiaobing/msxiaoiceapi$ python3 xiaoiceapi.py 
 * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
[2017-07-14 05:54:27,984] ERROR in app: Exception on / [GET]
Traceback (most recent call last):
  File "/home/aaaaa/.virtualenvs/env/lib/python3.5/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/aaaaa/.virtualenvs/env/lib/python3.5/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/aaaaa/.virtualenvs/env/lib/python3.5/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/aaaaa/.virtualenvs/env/lib/python3.5/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/home/aaaaa/.virtualenvs/env/lib/python3.5/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/aaaaa/.virtualenvs/env/lib/python3.5/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "xiaoiceapi.py", line 95, in index
    return jsonify(ans)
  File "/home/aaaaa/.virtualenvs/env/lib/python3.5/site-packages/flask/json.py", line 263, in jsonify
    (dumps(data, indent=indent, separators=separators), '\n'),
  File "/home/aaaaa/.virtualenvs/env/lib/python3.5/site-packages/flask/json.py", line 123, in dumps
    rv = _json.dumps(obj, **kwargs)
  File "/usr/lib/python3.5/json/__init__.py", line 237, in dumps
    **kw).encode(obj)
  File "/usr/lib/python3.5/json/encoder.py", line 201, in encode
    chunks = list(chunks)
  File "/usr/lib/python3.5/json/encoder.py", line 429, in _iterencode
    yield from _iterencode_dict(o, _current_indent_level)
  File "/usr/lib/python3.5/json/encoder.py", line 403, in _iterencode_dict
    yield from chunks
  File "/usr/lib/python3.5/json/encoder.py", line 436, in _iterencode
    o = _default(o)
  File "/home/aaaaa/.virtualenvs/env/lib/python3.5/site-packages/flask/json.py", line 80, in default
    return _json.JSONEncoder.default(self, o)
  File "/usr/lib/python3.5/json/encoder.py", line 180, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: PermissionError(13, 'Permission denied') is not JSON serializable
127.0.0.1 - - [14/Jul/2017 05:54:27] "GET /?que=%E4%BD%A0%E6%98%AF%E8%B0%81 HTTP/1.1" 500 -
```
服务器500错误

**Comment by yanwii** [comment]
你是用的测试账号吗,如果是的,那请用你自己的账号,测试账号过期了.

**Comment by skkep** [comment]
我确实是用自己账号登陆的，然后抓包得到的，你最近测试过了吗？是不是这个方法被封了，我看现在的接口是先拿到mid，然后用mid拉消息

**Comment by yanwii** [comment]
我测试了,应该是没装xpath页面解析不出来
`soup = BeautifulSoup(response.json()['data']['html'], "lxml")`
->
`soup = BeautifulSoup(response.json()['data']['html'], "html.parser")`

**Comment by skkep** [comment]
刚刚替换了，变成了超时，算了我也不是很熟悉python3，我有时间写个其他语言的吧，到时候再来请教你！

**Comment by skkep** [comment]
这是我用PHP实现的，借鉴了你的项目，请多多指教！
http://git.oschina.net/van404/xiaobingrobot

**Comment by yanwii** [comment]
学习了!
